name: Generate Profile Assets
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update cards and snake
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Summary Cards
      - uses: actions/checkout@v6
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

      # Snake Animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
